disabled_rules:
 - identifier_name
 - line_length
 - cyclomatic_complexity
 - conditional_returns_on_newline

opt_in_rules:
 - array_init
 - convenience_type
 - discouraged_object_literal
 - empty_collection_literal
 - empty_count
 - empty_string
 - explicit_init
 - legacy_multiple
 - legacy_random
 - literal_expression_end_indentation
 - modifier_order
 - multiline_function_chains
 - operator_usage_whitespace
 - override_in_extension
 - redundant_type_annotation
 - toggle_bool
 - yoda_condition
 - conditional_returns_on_newline
 - shorthand_optional_binding
